// Get a reference to the "Generate Password" button element
let generateBtn = document.getElementById("generate");
// Add a "click" event listener to the button that will display a new password
generateBtn.addEventListener("click", displayNewPassword);

/**
 * This `click` event handler function will generate a new password
 * and then display it as the value for the `#password` element
 * @returns {void} Nothing
 */

// Define a function that will output the password and push it to the screen.
function displayNewPassword() {
  let criteria = getCriteria();
  let password = generatePassword(criteria);
  let passwordText = document.getElementById("password");
  passwordText.value = password;
}

// Define a function that asks the user for password generation criteria, and logs the answers as an array.
// Ask for how long the password should be and assign the answer to a variable.
function getCriteria() {
  let lowercaseYesNo = confirm(
    "Include lowercase letters? Ok = Yes, Cancel = No"
  );
  let uppercaseYesNo = confirm(
    "Include uppercase letters? Ok = Yes, Cancel = No"
  );
  let numbersYesNo = confirm("Include numbers? Ok = Yes, Cancel = No");
  let specialYesNo = confirm(
    "Include special characters? Ok = Yes, Cancel = No"
  );
  var howLong = prompt(
    "How long should your password be? Must be between 8 and 128 characters long."
  );
  // Continually ask user for input until the response meeets length criteria.
  while (howLong < 8 || howLong > 128) {
    var howLong = prompt(
      "Your password must be between 8 and 128 Character long."
    );
  }
  userCriteria = [];
  if (lowercaseYesNo === true) {
    userCriteria.push("lowercase");
  }
  if (uppercaseYesNo === true) {
    userCriteria.push("uppercase");
  }
  if (numbersYesNo === true) {
    userCriteria.push("numbers");
  }
  if (specialYesNo === true) {
    userCriteria.push("special");
  }
  console.log(userCriteria);
  console.log(howLong);
  return userCriteria;
}

// Define a function that will take an array that was generated by getCriteria() and assigned to a variable,
// and generate a randomized passwords based on the contents of the array.
function generatePassword(criteria) {
  // Define variables that store all the possible characters to be used in password generation.
  let specialCharacters = [
    " ",
    "!",
    '"',
    "#",
    "$",
    "%",
    "&",
    "'",
    "(",
    ")",
    "*",
    "+",
    ",",
    "-",
    ".",
    "/",
    ":",
    ";",
    "<",
    "=",
    ">",
    "?",
    "@",
    "[",
    "\\",
    "]",
    "^",
    "_",
    "`",
    "{",
    "|",
    "}",
    "~",
  ];
  let numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];
  let lowercaseLetters = [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
  ];
  let uppercaseLetters = [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
  ];
  // Define a new array to be used for the final password generation.
  let concatArray = [];
  // Check the user's criteria responses, and concatenate the empty array with the relevant character arrays.
  // Use the spread operator (...) to spread out the items in each individual array into different arguments
  // and push them to the new array.
  if (criteria.includes("lowercase") === true) {
    concatArray.push(...lowercaseLetters);
  }
  if (criteria.includes("uppercase") === true) {
    concatArray.push(...uppercaseLetters);
  }
  if (criteria.includes("special") === true) {
    concatArray.push(...specialCharacters);
  }
  if (criteria.includes("numbers") === true) {
    concatArray.push(...numbers);
  }
  console.log(concatArray);
  // Use a for loop to create a new array based on the resulted array, with scrambled characters.
  // For length, use the user defined value in howLong.
}
